stages:
  - build
  - deploy

slide_gen:
  stage: build
  image:
    name: marpteam/marp-cli
    entrypoint: [""]
  script :
    - mkdir build/
    - export MARP_USER="$(id -u):$(id -g)"
    - /home/marp/.cli/docker-entrypoint -I . -o build/
  artifacts:
    paths:
      - "build/"

pages:
  stage: deploy
  script:
    - mv build public
    - mv img public/img
    - mv public/PITCHME.html public/index.html
  artifacts:
    paths:
      - public
  dependencies:
    - slide_gen
